import {
  mdiAccountGroup,
  mdiBadminton,
  mdiBasket,
  mdiBasketball,
  mdiBeer,
  mdiBike,
  mdiBowling,
  mdiCamera,
  mdiCampfire,
  mdiChessPawn,
  mdiCoffee,
  mdiDumbbell,
  mdiFish,
  mdiGamepadVariant,
  mdiGlassWine,
  mdiGuitarElectric,
  mdiHeadQuestion,
  mdiHiking,
  mdiHumanFemaleDance,
  mdiKayaking,
  mdiLaptop,
  mdiMicrophoneVariant,
  mdiMovieOpen,
  mdiMushroom,
  mdiMusic,
  mdiPalette,
  mdiPartyPopper,
  mdiPotMix,
  mdiRollerSkate,
  mdiRunFast,
  mdiSilverwareForkKnife,
  mdiSoccer,
  mdiSwim,
  mdiTableTennis,
  mdiTennis,
  mdiTools,
  mdiTranslateVariant,
  mdiVolleyball,
  mdiWalk,
  mdiYoga,
} from "@mdi/js";

export const materialEventArtworkPaths: Readonly<Record<string, string>> = {
  VB: mdiVolleyball,
  FB: mdiSoccer,
  BB: mdiBasketball,
  TN: mdiTennis,
  GY: mdiDumbbell,
  RN: mdiRunFast,
  CY: mdiBike,
  BD: mdiBadminton,
  TT: mdiTableTennis,
  YG: mdiYoga,
  CF: mdiCoffee,
  MV: mdiMovieOpen,
  BW: mdiBowling,
  BG: mdiGamepadVariant,
  CH: mdiChessPawn,
  KR: mdiMicrophoneVariant,
  SK: mdiRollerSkate,
  BR: mdiBeer,
  QZ: mdiHeadQuestion,
  WN: mdiGlassWine,
  CN: mdiMusic,
  FS: mdiPartyPopper,
  DN: mdiHumanFemaleDance,
  HK: mdiHiking,
  WK: mdiWalk,
  CT: mdiWalk,
  SW: mdiSwim,
  PC: mdiBasket,
  CP: mdiCampfire,
  FI: mdiFish,
  KY: mdiKayaking,
  MP: mdiMushroom,
  DR: mdiSilverwareForkKnife,
  LX: mdiTranslateVariant,
  CW: mdiLaptop,
  MT: mdiAccountGroup,
  AR: mdiPalette,
  PH: mdiCamera,
  CR: mdiPotMix,
  JM: mdiGuitarElectric,
  WS: mdiTools,
};
