import { createClient } from "https://esm.sh/@supabase/supabase-js@2.108.2";
import { appendTelegramPostShareButton, buildTelegramEventCard, type TelegramEventCardInput, type TelegramEventLanguage } from "../../../api/_shared/telegram-event-card.ts";
import { activityDateLabel, activityEndsAt, buildCitySendPhotoPayload, readCityTelegramPublicationState, resolveCityTelegramChatId, resolveCityTelegramTopicId, withCityTelegramPublicationState, type CityTelegramPublicationState } from "../../../api/_shared/telegram-city-publication-core.ts";

type Lang=TelegramEventLanguage; type DB=ReturnType<typeof createClient>; type Tg=<T>(m:string,b?:Record<string,unknown>)=>Promise<T>;
type Claims={aud?:string;exp?:number;iss?:string;role?:string;go_irl_user_key?:string;go_irl_role?:string};
type A={id:string;category_id:string|null;activity_ru:string;activity_cs:string;title_ru:string|null;title_cs:string|null;description_ru:string;description_cs:string;event_date:string;event_time:string|null;city_id:string|null;address:string;location_url:string|null;activity_type:string|null;visibility:string;metadata:Record<string,unknown>|null;organizer_key:string};
type B={url:string|null;telegram_chat_id:number|null;telegram_chat_title:string|null;telegram_message_thread_id:number|null;topic_delete_after:string|null;topic_deleted_at:string|null}; type Chat={id:number;type:string;title?:string;username?:string;invite_link?:string;is_forum?:boolean};
const mediaOrigin="https://go-irl-1-1.vercel.app", langs:readonly Lang[]=["ru","uk","cs","en","pl","sk"], uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const names:Array<[string,string,string,string,string]>=[
["Волейбол","Волейбол","Volejbal","Volleyball","🏐"],["Футбол","Футбол","Fotbal","Football","⚽"],["Баскетбол","Баскетбол","Basketbal","Basketball","🏀"],["Теннис","Теніс","Tenis","Tennis","🎾"],["Тренажёрный зал","Тренажерний зал","Posilovna","Gym","🏋️"],["Бег","Біг","Běh","Running","🏃"],["Велосипед","Велосипед","Kolo","Cycling","🚴"],["Бадминтон","Бадмінтон","Badminton","Badminton","🏸"],["Настольный теннис","Настільний теніс","Stolní tenis","Table tennis","🏓"],["Йога","Йога","Jóga","Yoga","🧘"],
["Кофе","Кава","Káva","Coffee","☕"],["Кино","Кіно","Kino","Cinema","🎬"],["Боулинг","Боулінг","Bowling","Bowling","🎳"],["Настольные игры","Настільні ігри","Deskové hry","Board games","🎲"],["Шахматы","Шахи","Šachy","Chess","♟️"],["Караоке","Караоке","Karaoke","Karaoke","🎤"],["Ролики","Ролики","Inline bruslení","Inline skating","🛼"],
["Идём на пиво","Йдемо на пиво","Jdeme na pivo","Let's get a beer","🍺"],["Паб-квиз","Паб-квіз","Pub kvíz","Pub quiz","🧠"],["Винный вечер","Винний вечір","Večer s vínem","Wine evening","🍷"],["Концерт","Концерт","Koncert","Concert","🎵"],["Фестиваль","Фестиваль","Festival","Festival","🎪"],["Танцы","Танці","Tanec","Dancing","💃"],
["Поход","Похід","Výlet","Hike","🥾"],["Прогулка в парке","Прогулянка в парку","Procházka v parku","Park walk","🚶"],["Плавание","Плавання","Plavání","Swimming","🏊"],["Пикник","Пікнік","Piknik","Picnic","🧺"],["Кемпинг","Кемпінг","Kempování","Camping","⛺"],["Рыбалка","Риболовля","Rybaření","Fishing","🎣"],["Каяки","Каяки","Kajaky","Kayaking","🛶"],
["Прогулка","Прогулянка","Procházka","Walk","🚶"],["Ужин","Вечеря","Večeře","Dinner","🍽️"],["Языковой обмен","Мовний обмін","Jazyková výměna","Language exchange","🗣️"],["Коворкинг","Коворкінг","Coworking","Coworking","💻"],["Новые знакомства","Нові знайомства","Nová seznámení","Meet new people","🤝"],["Рисование","Малювання","Malování","Drawing","🎨"],["Фотопрогулка","Фотопрогулянка","Fotoprocházka","Photo walk","📸"],["Керамика","Кераміка","Keramika","Ceramics","🏺"],["Музыкальный джем","Музичний джем","Hudební jam","Music jam","🎸"],["Мастерская","Майстерня","Dílna","Workshop","🧶"]];
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}), eq=(a:string,b:string)=>{if(!a||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const bytes=(s:string)=>{const n=s.replaceAll("-","+").replaceAll("_","/");return Uint8Array.from(atob(n.padEnd(Math.ceil(n.length/4)*4,"=")),c=>c.charCodeAt(0))}, b64=(a:Uint8Array)=>{let s="";for(const b of a)s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"")}, dec=<T>(s:string):T=>JSON.parse(new TextDecoder().decode(bytes(s))) as T;
const verify=async(t:string,secret:string):Promise<Claims|null>=>{try{const p=t.split(".");if(p.length!==3||!secret)return null;const h=dec<{alg?:string;typ?:string}>(p[0]),c=dec<Claims>(p[1]);if(h.alg!=="HS256"||h.typ!=="JWT")return null;const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]),ok=await crypto.subtle.verify("HMAC",k,bytes(p[2]),new TextEncoder().encode(`${p[0]}.${p[1]}`));return ok&&c.exp&&c.exp>Date.now()/1000&&c.iss==="go-irl-supabase-edge"&&c.aud==="authenticated"&&c.role==="authenticated"&&c.go_irl_user_key?c:null}catch{return null}};
const cardToken=async(id:string,l:Lang,secret:string)=>{const card={eventId:id,language:l} as TelegramEventCardInput,p=b64(new TextEncoder().encode(JSON.stringify({card,expiresAt:Date.now()+3600000}))),k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return`${p}.${b64(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(p))))}`};
const api=(bot:string):Tg=>async<T>(m:string,b:Record<string,unknown>={})=>{const r=await fetch(`https://api.telegram.org/bot${bot}/${m}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)}),p=await r.json() as{ok?:boolean;result?:T;description?:string};if(!r.ok||!p.ok||p.result===undefined)throw new Error(`telegram_${m}_failed:${p.description||r.status}`);return p.result}, detail=(e:unknown)=>e instanceof Error?e.message.replace(/Bearer\s+[^\s]+/gi,"***").slice(0,500)||"unknown":"unknown";
const l4=(l:Lang):"ru"|"uk"|"cs"|"en"=>l==="pl"?"en":l==="sk"?"cs":l, norm=(s:string|null|undefined)=>(s||"").trim().toLocaleLowerCase(), opt=(a:A)=>{const set=new Set([a.activity_ru,a.activity_cs,a.title_ru,a.title_cs].map(norm).filter(Boolean));return names.find(n=>n.slice(0,4).some(x=>set.has(norm(x))))}, act=(a:A,l:Lang)=>{const o=opt(a),i={ru:0,uk:1,cs:2,en:3}[l4(l)];return o?.[i]||(l4(l)==="cs"?a.activity_cs:a.activity_ru)};
const date=(v:string,l:Lang)=>{const d=new Date(`${v}T12:00:00Z`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat(({ru:"ru-RU",uk:"uk-UA",cs:"cs-CZ",en:"en-GB",pl:"pl-PL",sk:"sk-SK"}as const)[l],{day:"numeric",month:"short",timeZone:"UTC"}).format(d).replace(/\.$/,"")}, city=(id:string|null,l:Lang)=>({praha:{ru:"Прага",uk:"Прага",cs:"Praha",en:"Prague",pl:"Praga",sk:"Praha"},olomouc:{ru:"Оломоуц",uk:"Оломоуц",cs:"Olomouc",en:"Olomouc",pl:"Ołomuniec",sk:"Olomouc"},kharkiv:{ru:"Харьков",uk:"Харків",cs:"Charkov",en:"Kharkiv",pl:"Charków",sk:"Charkov"}}as Record<string,Record<Lang,string>>)[id||""]?.[l]||id||"GO IRL", cityLabel=(id:string|null)=>id==="praha"?"Praha":id==="olomouc"?"Olomouc":id==="kharkiv"?"Kharkiv":id||"GO IRL";
const load=async(db:DB,id:string)=>{const q=await db.from("activities").select("id,category_id,activity_ru,activity_cs,title_ru,title_cs,description_ru,description_cs,event_date,event_time,city_id,address,location_url,activity_type,visibility,metadata,organizer_key").eq("id",id).maybeSingle();if(q.error)throw q.error;return q.data as A|null}, meta=async(db:DB,id:string,f:(m:Record<string,unknown>|null)=>Record<string,unknown>)=>{const q=await db.from("activities").select("metadata").eq("id",id).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error("activity_not_found");const u=await db.from("activities").update({metadata:f((q.data.metadata||null)as Record<string,unknown>|null)}).eq("id",id);if(u.error)throw u.error};
const chatUrl=(v:string|null|undefined)=>{const s=v?.trim()||"";return /^https:\/\/t\.me\/(?:joinchat\/[-_A-Za-z0-9]+|\+[-_A-Za-z0-9]+|[A-Za-z0-9_]{5,})(?:\/[0-9]+)?$/.test(s)?s:null}, postUrl=(c:Chat,messageId:number)=>{const u=(c.username||"").replace(/^@/,"");return /^[A-Za-z0-9_]{5,}$/.test(u)?`https://t.me/${u}/${messageId}`:null}, bind=async(db:DB,t:Tg,a:A,chatId:number)=>{const c=await t<Chat>("getChat",{chat_id:chatId});if(c.id!==chatId||!["group","supergroup"].includes(c.type))throw new Error("telegram_city_chat_invalid");let url=/^[A-Za-z0-9_]{5,}$/.test(c.username||"")?`https://t.me/${c.username}`:chatUrl(c.invite_link);if(!url){const x=await t<{invite_link:string}>("createChatInviteLink",{chat_id:chatId,name:`GO IRL ${a.id}`.slice(0,32)});url=chatUrl(x.invite_link)}if(!url)throw new Error("telegram_city_chat_url_unavailable");const now=new Date().toISOString(),q=await db.from("activity_external_telegram_chats").upsert({activity_id:a.id,url,attached_by_user_key:a.organizer_key,telegram_chat_id:chatId,telegram_chat_type:c.type,telegram_chat_title:c.title||cityLabel(a.city_id),bound_at:now,updated_at:now},{onConflict:"activity_id"});if(q.error)throw q.error;return{chat:c,url}};
const share=async(a:A,l:Lang,bot:string)=>{const image=new URL("/api/telegram/event-share-card",mediaOrigin);image.searchParams.set("mode","persisted");image.searchParams.set("token",await cardToken(a.id,l,bot));const name=act(a,l),c=l4(l),synthetic:TelegramEventCardInput={eventId:a.id,title:name,activity:name,date:date(a.event_date,l),eventDate:a.event_date,time:(a.event_time||"00:00").slice(0,5),address:a.address,participants:0,capacity:0,icon:opt(a)?.[4]||"✨",inviteUrl:`https://t.me/GOirl_bot?startapp=${encodeURIComponent(a.id)}`,mapUrl:a.location_url||undefined,city:city(a.city_id,l),price:0,level:"",format:"",environment:"",isSport:a.activity_type==="sport",language:l,description:a.activity_type==="sport"?(c==="cs"?a.description_cs:a.description_ru):undefined};return buildTelegramEventCard(synthetic,image.toString())};
const publish=async(db:DB,t:Tg,bot:string,id:string,l:Lang,user?:string)=>{
  const a=await load(db,id);
  if(!a)return{published:false,skipped:"missing"};
  if(user&&a.organizer_key!==user)throw new Error("organizer_required");
  if(a.visibility!=="public")return{published:false,skipped:"visibility"};
  const chatId=resolveCityTelegramChatId(a.city_id);
  if(!chatId)return{published:false,skipped:"city"};
  const messageThreadId=resolveCityTelegramTopicId(a.city_id,a);
  const old=readCityTelegramPublicationState(a.metadata),card=await share(a,l,bot);
  if(old?.active&&old.activityId===a.id&&old.chatId===chatId&&(old.messageThreadId??null)===messageThreadId){
    const binding=await bind(db,t,a,chatId),url=postUrl(binding.chat,old.messageId),replyMarkup=url?appendTelegramPostShareButton(card.reply_markup,l,url):card.reply_markup;
    await t("editMessageMedia",{chat_id:chatId,message_id:old.messageId,media:{type:"photo",media:card.photo_url,caption:card.caption||""},reply_markup:replyMarkup});
    return{published:true,reused:true,updated:true,mediaUpdated:true,mediaUnchanged:false,pinned:false,chatId,messageId:old.messageId,messageThreadId};
  }
  const superseded=old?.active&&old.activityId===a.id?old:null;
  const m=await t<{message_id:number}>("sendPhoto",buildCitySendPhotoPayload(chatId,card,messageThreadId));
  if(!Number.isSafeInteger(m.message_id)||m.message_id<=0)throw new Error("telegram_send_photo_invalid_response");
  try{
    const binding=await bind(db,t,a,chatId),url=postUrl(binding.chat,m.message_id);
    if(url)await t("editMessageReplyMarkup",{chat_id:chatId,message_id:m.message_id,reply_markup:appendTelegramPostShareButton(card.reply_markup,l,url)});
    const now=new Date().toISOString(),s:CityTelegramPublicationState={
      activityId:a.id,
      active:true,
      chatId,
      messageId:m.message_id,
      ...(messageThreadId?{messageThreadId}:{}),
      pinnedAt:now,
      unpinAt:activityEndsAt(a).toISOString(),
    };
    await meta(db,a.id,x=>withCityTelegramPublicationState(x,s));
    if(superseded){
      try{await t("unpinChatMessage",{chat_id:superseded.chatId,message_id:superseded.messageId})}catch{/* Best-effort cleanup after replacement. */}
      try{await t("deleteMessage",{chat_id:superseded.chatId,message_id:superseded.messageId})}catch{/* Best-effort cleanup after replacement. */}
    }
    return{published:true,reused:false,mediaUnchanged:true,pinned:false,chatId,messageId:m.message_id,messageThreadId,unpinAt:s.unpinAt};
  }catch(e){
    try{await t("deleteMessage",{chat_id:chatId,message_id:m.message_id})}catch{/* Best-effort rollback; preserve the original publication error. */}
    throw e;
  }
};
const unpin=async(db:DB,id:string,user?:string)=>{const a=await load(db,id);if(!a)return{unpinned:false,skipped:"missing"};if(user&&a.organizer_key!==user)throw new Error("organizer_required");const s=readCityTelegramPublicationState(a.metadata);if(!s||s.activityId!==a.id)return{unpinned:false,skipped:"untracked"};if(!s.active)return{unpinned:false,alreadyUnpinned:true,chatId:s.chatId,messageId:s.messageId};const n={...s,active:false,unpinAt:activityEndsAt(a).toISOString(),unpinnedAt:new Date().toISOString()};await meta(db,a.id,x=>withCityTelegramPublicationState(x,n));return{unpinned:true,chatId:s.chatId,messageId:s.messageId,unpinAt:n.unpinAt}}, unpinDue=async(db:DB,limit=100)=>{const q=await db.from("activities").select("id,category_id,activity_ru,activity_cs,title_ru,title_cs,description_ru,description_cs,event_date,event_time,city_id,address,location_url,activity_type,visibility,metadata,organizer_key").contains("metadata",{cityTelegramPublication:{active:true}}).limit(Math.max(1,Math.min(limit,200)));if(q.error)throw q.error;let checked=0,unpinned=0,failed=0;for(const a of(q.data||[])as A[]){const s=readCityTelegramPublicationState(a.metadata);if(!s?.active||s.activityId!==a.id)continue;checked++;try{if(activityEndsAt(a).getTime()>Date.now())continue;await unpin(db,a.id);unpinned++}catch{failed++}}return{checked,unpinned,failed}};
const tgUser=async(db:DB,k:string)=>{const q=await db.from("user_provider_identities").select("provider_user_id").eq("user_key",k).eq("provider","telegram").eq("status","active").not("consented_at","is",null).maybeSingle();if(q.error)throw q.error;const id=Number(q.data?.provider_user_id);return Number.isSafeInteger(id)&&id>0?id:null}, sync=async(db:DB,t:Tg,id:string,actor:string,member?:string)=>{const a=await load(db,id);if(!a)return{prompted:false,skipped:"missing"};const user=member||actor;if(member&&user!==actor&&a.organizer_key!==actor)throw new Error("organizer_required");const m=await db.from("activity_members").select("status").eq("activity_id",id).eq("user_key",user).maybeSingle();if(m.error)throw m.error;if(m.data?.status!=="joined")return{prompted:false,skipped:"not_joined"};const uid=await tgUser(db,user);if(!uid)return{prompted:false,skipped:"telegram_identity"};let chatId:number|null,url:string|null;if(a.visibility==="public"){chatId=resolveCityTelegramChatId(a.city_id);if(!chatId)return{prompted:false,skipped:"city"};url=(await bind(db,t,a,chatId)).url}else{const q=await db.from("activity_external_telegram_chats").select("url,telegram_chat_id,telegram_chat_title,telegram_message_thread_id,topic_delete_after,topic_deleted_at").eq("activity_id",id).maybeSingle();if(q.error)throw q.error;const b=q.data as B|null;chatId=b?.telegram_chat_id||null;url=chatUrl(b?.url);if(!chatId||!url||b?.topic_deleted_at)return{prompted:false,skipped:"activity_chat"}}const st=await t<{status?:string}>("getChatMember",{chat_id:chatId,user_id:uid});if(st.status&&!["left","kicked"].includes(st.status))return{prompted:false,alreadyMember:true,chatId};let invite=url;try{const x=await t<{invite_link:string}>("createChatInviteLink",{chat_id:chatId,name:`GO IRL ${a.id}`.slice(0,32),expire_date:Math.floor(Date.now()/1000)+1800,member_limit:1});invite=chatUrl(x.invite_link)||url}catch{/* Best-effort invite refresh; keep the existing trusted URL fallback. */}await t("sendMessage",{chat_id:uid,text:a.visibility==="public"?`Ты подтверждён в событии GO IRL. Вступи в городской Telegram-чат ${cityLabel(a.city_id)}, если хочешь получать обновления.`:"Ты подтверждён в событии GO IRL. Telegram-чат события доступен по кнопке ниже.",reply_markup:{inline_keyboard:[[{text:"Вступить в Telegram-чат",url:invite}]]}});return{prompted:true,chatId}};
const topicUrl=(chatId:number,n:number)=>{const s=String(chatId);if(!s.startsWith("-100")||!Number.isSafeInteger(n)||n<=0)throw new Error("telegram_forum_topic_url_invalid");return`https://t.me/c/${s.slice(4)}/${n}`}, topic=async(db:DB,t:Tg,id:string,user:string)=>{const a=await load(db,id);if(!a)throw new Error("activity_not_found");if(a.organizer_key!==user)throw new Error("organizer_required");if(a.visibility!=="public")throw new Error("activity_not_public");const chatId=resolveCityTelegramChatId(a.city_id);if(!chatId)throw new Error("city_not_supported");const q=await db.from("activity_external_telegram_chats").select("url,telegram_chat_id,telegram_chat_title,telegram_message_thread_id,topic_delete_after,topic_deleted_at").eq("activity_id",id).maybeSingle();if(q.error)throw q.error;const old=q.data as B|null;if(old?.telegram_chat_id===chatId&&old.telegram_message_thread_id&&!old.topic_deleted_at&&old.url)return{inviteUrl:old.url,topicUrl:topicUrl(chatId,old.telegram_message_thread_id),messageThreadId:old.telegram_message_thread_id,title:old.telegram_chat_title||cityLabel(a.city_id),deleteAfter:old.topic_delete_after||new Date(activityEndsAt(a).getTime()+86400000).toISOString(),reused:true};const b=await bind(db,t,a,chatId);if(b.chat.type!=="supergroup"||!b.chat.is_forum)throw new Error("telegram_event_supergroup_forum_required");const title=`${cityLabel(a.city_id)} / ${act(a,"cs")||a.title_cs||a.title_ru||"GO IRL event"} / ${activityDateLabel(a.event_date)}`.slice(0,128),created=await t<{message_thread_id:number;name?:string}>("createForumTopic",{chat_id:chatId,name:title}),now=new Date().toISOString(),deleteAfter=new Date(activityEndsAt(a).getTime()+86400000).toISOString(),save=await db.from("activity_external_telegram_chats").upsert({activity_id:a.id,url:b.url,attached_by_user_key:a.organizer_key,telegram_chat_id:chatId,telegram_chat_type:b.chat.type,telegram_chat_title:b.chat.title||cityLabel(a.city_id),bound_at:now,telegram_message_thread_id:created.message_thread_id,topic_created_at:now,topic_delete_after:deleteAfter,topic_deleted_at:null,updated_at:now},{onConflict:"activity_id"});if(save.error)throw save.error;const p=readCityTelegramPublicationState(a.metadata);if(p?.active&&p.chatId===chatId){const c=await t<{message_id:number}>("copyMessage",{chat_id:chatId,from_chat_id:chatId,message_id:p.messageId,message_thread_id:created.message_thread_id});await t("pinChatMessage",{chat_id:chatId,message_id:c.message_id,disable_notification:true})}return{inviteUrl:b.url,topicUrl:topicUrl(chatId,created.message_thread_id),messageThreadId:created.message_thread_id,title:created.name||title,deleteAfter,reused:false}};
export const callCityPublicationEdge=async({authorization,body,supabaseUrl,serviceRoleKey,jwtSecret,botToken}:{authorization:string;body:Record<string,unknown>;supabaseUrl:string;serviceRoleKey:string;jwtSecret:string;botToken:string})=>{if(!supabaseUrl||!serviceRoleKey||!jwtSecret||!botToken)return json({error:"city_telegram_unavailable"},503);const bearer=authorization.match(/^Bearer\s+(.+)$/i)?.[1]?.trim()||"",service=eq(bearer,serviceRoleKey),claims=service?null:await verify(bearer,jwtSecret);if(!service&&!claims)return json({error:"access_denied"},401);const action=typeof body.action==="string"?body.action:"",db=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}}),t=api(botToken);try{if(action==="unpin_due"){if(!service)return json({error:"service_role_required"},403);return json({ok:true,...await unpinDue(db,Number.isInteger(body.limit)?Number(body.limit):100)})}const id=typeof body.activityId==="string"&&uuid.test(body.activityId.trim())?body.activityId.trim():"";if(!id)return json({error:"invalid_event_id"},400);if(action==="publish")return json(await publish(db,t,botToken,id,langs.includes(body.language as Lang)?body.language as Lang:"cs",claims?.go_irl_user_key));if(action==="unpin_activity"){const admin=claims?.go_irl_role==="admin"||claims?.go_irl_role==="superadmin";return json(await unpin(db,id,service||admin?undefined:claims?.go_irl_user_key))}if(action==="sync_joined_member"){if(!claims?.go_irl_user_key)return json({error:"user_session_required"},403);return json(await sync(db,t,id,claims.go_irl_user_key,typeof body.memberUserKey==="string"&&body.memberUserKey.trim()?body.memberUserKey.trim().slice(0,180):undefined))}if(action==="create_city_topic"){if(!claims?.go_irl_user_key)return json({error:"user_session_required"},403);return json({topic:await topic(db,t,id,claims.go_irl_user_key)})}return json({error:"invalid_action"},400)}catch(e){const d=detail(e);if(d==="organizer_required")return json({error:"organizer_required"},403);if(d==="activity_not_public")return json({error:"activity_not_public"},409);return json({error:"city_telegram_operation_failed",detail:d},502)}};
