import type { Activity, Category } from "./types.js";

export const categories: Category[] = [
  { id: "sport", icon: "🏆", name: { ru: "Спорт", uk: "Спорт", cs: "Sport", en: "Sport" } },
  { id: "activities", icon: "🎉", name: { ru: "Активности", uk: "Активності", cs: "Aktivity", en: "Activities" } },
  { id: "party", icon: "🍻", name: { ru: "Вечеринки", uk: "Вечірки", cs: "Večírky", en: "Parties" } },
  { id: "nature", icon: "🌿", name: { ru: "Природа", uk: "Природа", cs: "Příroda", en: "Nature" } },
  { id: "social", icon: "❤️", name: { ru: "Общение", uk: "Спілкування", cs: "Setkání", en: "Social" } },
  { id: "creativity", icon: "🎨", name: { ru: "Творчество", uk: "Творчість", cs: "Tvorba", en: "Creativity" } },
];

export const activityOptions: Record<string, Array<{ icon: string; name: Category["name"] }>> = {
  sport: [
    { icon: "🏐", name: { ru: "Волейбол", uk: "Волейбол", cs: "Volejbal", en: "Volleyball" } },
    { icon: "⚽", name: { ru: "Футбол", uk: "Футбол", cs: "Fotbal", en: "Football" } },
    { icon: "🏀", name: { ru: "Баскетбол", uk: "Баскетбол", cs: "Basketbal", en: "Basketball" } },
    { icon: "🎾", name: { ru: "Теннис", uk: "Теніс", cs: "Tenis", en: "Tennis" } },
    { icon: "🏋️", name: { ru: "Тренажёрный зал", uk: "Тренажерний зал", cs: "Posilovna", en: "Gym" } },
    { icon: "🏃", name: { ru: "Бег", uk: "Біг", cs: "Běh", en: "Running" } },
    { icon: "🚴", name: { ru: "Велосипед", uk: "Велосипед", cs: "Kolo", en: "Cycling" } },
    { icon: "🏸", name: { ru: "Бадминтон", uk: "Бадмінтон", cs: "Badminton", en: "Badminton" } },
    { icon: "🏓", name: { ru: "Настольный теннис", uk: "Настільний теніс", cs: "Stolní tenis", en: "Table tennis" } },
    { icon: "🧘", name: { ru: "Йога", uk: "Йога", cs: "Jóga", en: "Yoga" } },
  ],
  activities: [
    { icon: "☕", name: { ru: "Кофе", uk: "Кава", cs: "Káva", en: "Coffee" } },
    { icon: "🎬", name: { ru: "Кино", uk: "Кіно", cs: "Kino", en: "Cinema" } },
    { icon: "🎳", name: { ru: "Боулинг", uk: "Боулінг", cs: "Bowling", en: "Bowling" } },
    { icon: "🎲", name: { ru: "Настольные игры", uk: "Настільні ігри", cs: "Deskové hry", en: "Board games" } },
    { icon: "♟️", name: { ru: "Шахматы", uk: "Шахи", cs: "Šachy", en: "Chess" } },
    { icon: "🎤", name: { ru: "Караоке", uk: "Караоке", cs: "Karaoke", en: "Karaoke" } },
    { icon: "🛼", name: { ru: "Ролики", uk: "Ролики", cs: "Inline bruslení", en: "Inline skating" } },
  ],
  party: [
    { icon: "🍺", name: { ru: "Идём на пиво", uk: "Йдемо на пиво", cs: "Jdeme na pivo", en: "Let's get a beer" } },
    { icon: "🧠", name: { ru: "Паб-квиз", uk: "Паб-квіз", cs: "Pub kvíz", en: "Pub quiz" } },
    { icon: "🍷", name: { ru: "Винный вечер", uk: "Винний вечір", cs: "Večer s vínem", en: "Wine evening" } },
    { icon: "🎵", name: { ru: "Концерт", uk: "Концерт", cs: "Koncert", en: "Concert" } },
    { icon: "🎪", name: { ru: "Фестиваль", uk: "Фестиваль", cs: "Festival", en: "Festival" } },
    { icon: "💃", name: { ru: "Танцы", uk: "Танці", cs: "Tanec", en: "Dancing" } },
  ],
  nature: [
    { icon: "🥾", name: { ru: "Поход", uk: "Похід", cs: "Výlet", en: "Hike" } },
    { icon: "🚶", name: { ru: "Прогулка в парке", uk: "Прогулянка в парку", cs: "Procházka v parku", en: "Park walk" } },
    { icon: "🏊", name: { ru: "Плавание", uk: "Плавання", cs: "Plavání", en: "Swimming" } },
    { icon: "🧺", name: { ru: "Пикник", uk: "Пікнік", cs: "Piknik", en: "Picnic" } },
    { icon: "⛺", name: { ru: "Кемпинг", uk: "Кемпінг", cs: "Kempování", en: "Camping" } },
    { icon: "🎣", name: { ru: "Рыбалка", uk: "Риболовля", cs: "Rybaření", en: "Fishing" } },
    { icon: "🛶", name: { ru: "Каяки", uk: "Каяки", cs: "Kajaky", en: "Kayaking" } },
  ],
  social: [
    { icon: "🚶", name: { ru: "Прогулка", uk: "Прогулянка", cs: "Procházka", en: "Walk" } },
    { icon: "🍽️", name: { ru: "Ужин", uk: "Вечеря", cs: "Večeře", en: "Dinner" } },
    { icon: "🗣️", name: { ru: "Языковой обмен", uk: "Мовний обмін", cs: "Jazyková výměna", en: "Language exchange" } },
    { icon: "💻", name: { ru: "Коворкинг", uk: "Коворкінг", cs: "Coworking", en: "Coworking" } },
    { icon: "🤝", name: { ru: "Новые знакомства", uk: "Нові знайомства", cs: "Nová seznámení", en: "Meet new people" } },
  ],
  creativity: [
    { icon: "🎨", name: { ru: "Рисование", uk: "Малювання", cs: "Malování", en: "Drawing" } },
    { icon: "📸", name: { ru: "Фотопрогулка", uk: "Фотопрогулянка", cs: "Fotoprocházka", en: "Photo walk" } },
    { icon: "🏺", name: { ru: "Керамика", uk: "Кераміка", cs: "Keramika", en: "Ceramics" } },
    { icon: "🎸", name: { ru: "Музыкальный джем", uk: "Музичний джем", cs: "Hudební jam", en: "Music jam" } },
    { icon: "🧶", name: { ru: "Мастерская", uk: "Майстерня", cs: "Dílna", en: "Workshop" } },
  ],
};

type ClosedBetaCategoryId = "sport" | "activities" | "social";

const hasEnglishName = (names: string[]) => (option: { name: Category["name"] }) => names.includes(option.name.en);

export const closedBetaCategories = categories.filter((category) =>
  (["sport", "activities", "social"]).includes(category.id),
);

export const closedBetaActivityOptions = {
  sport: activityOptions.sport.filter(hasEnglishName(["Volleyball", "Running"])),
  activities: activityOptions.activities.filter(hasEnglishName(["Coffee", "Board games", "Chess"])),
  social: activityOptions.social.filter(hasEnglishName(["Walk", "Language exchange"])),
} satisfies Record<ClosedBetaCategoryId, Array<{ icon: string; name: Category["name"] }>>;

const sportSeed = (
  id: string,
  icon: string,
  names: Activity["activity"],
  title: Activity["title"],
  description: Activity["description"],
  date: string,
  time: string,
  address: string,
  price: number,
  capacity: number,
  participants: number,
  sport: NonNullable<Activity["metadata"]>["sport"],
): Activity => ({
  id,
  type: "sport",
  categoryId: "sport",
  activity: {
    ru: `${icon} ${names.ru}`,
    uk: `${icon} ${names.uk}`,
    cs: `${icon} ${names.cs}`,
    en: `${icon} ${names.en}`,
  },
  title,
  description,
  date,
  time,
  cityId: id.includes("praha") ? "praha" : "olomouc",
  address,
  locationUrl: "",
  participantNote: "",
  price,
  capacity,
  participants,
  members: [],
  organizer: "GO IRL Demo",
  organizerKey: "demo:sport",
  visibility: "public",
  popular: participants >= 4,
  metadata: {
    sport,
  },
});

export const seedActivities: Activity[] = [
  sportSeed(
    "demo-sport-football",
    "⚽",
    { ru: "Футбол", uk: "Футбол", cs: "Fotbal", en: "Football" },
    { ru: "5 на 5 после работы", uk: "5 на 5 після роботи", cs: "5 na 5 po práci", en: "5-a-side after work" },
    {
      ru: "Лёгкая игра без жёсткой борьбы, собираем две команды.",
      uk: "Легка гра без жорсткої боротьби, збираємо дві команди.",
      cs: "Lehká hra bez tvrdých soubojů, skládáme dva týmy.",
      en: "Easy match without hard tackles, building two teams.",
    },
    "2026-07-08",
    "18:30",
    "Smetanovy sady, Olomouc",
    0,
    10,
    6,
    {
      sportType: "Football",
      level: "intermediate",
      format: "casual",
      environment: "outdoor",
      equipmentNeeded: true,
      equipment: "Мяч у организатора",
      bring: "Бутсы или удобные кроссовки, вода",
      requirements: "Без грубой игры",
      organizerTips: "Приходи за 10 минут до начала",
      durationMinutes: 90,
    },
  ),
  sportSeed(
    "demo-sport-volleyball",
    "🏐",
    { ru: "Волейбол", uk: "Волейбол", cs: "Volejbal", en: "Volleyball" },
    { ru: "Пляжный волейбол для новичков", uk: "Пляжний волейбол для новачків", cs: "Beach volejbal pro začátečníky", en: "Beginner beach volleyball" },
    {
      ru: "Спокойная игра, объясним правила и расставимся по уровню.",
      uk: "Спокійна гра, пояснимо правила і розставимося за рівнем.",
      cs: "Pohodová hra, vysvětlíme pravidla a rozdělíme se podle úrovně.",
      en: "Relaxed game, we explain rules and split by level.",
    },
    "2026-07-09",
    "17:45",
    "Beach Arena Olomouc",
    120,
    8,
    5,
    {
      sportType: "Volleyball",
      level: "beginner",
      format: "training",
      environment: "outdoor",
      equipmentNeeded: false,
      bring: "Спортивная одежда, вода",
      requirements: "Подходит без опыта",
      organizerTips: "Можно прийти одному",
      durationMinutes: 75,
    },
  ),
  sportSeed(
    "demo-sport-tennis-praha",
    "🎾",
    { ru: "Теннис", uk: "Теніс", cs: "Tenis", en: "Tennis" },
    { ru: "Парный теннис в Праге", uk: "Парний теніс у Празі", cs: "Čtyřhra v Praze", en: "Doubles tennis in Prague" },
    {
      ru: "Ищем двух игроков для пары, темп любительский.",
      uk: "Шукаємо двох гравців для пари, темп аматорський.",
      cs: "Hledáme dva hráče do čtyřhry, rekreační tempo.",
      en: "Looking for two doubles players, casual pace.",
    },
    "2026-07-10",
    "19:00",
    "Tenis Cibulka, Praha",
    180,
    4,
    2,
    {
      sportType: "Tennis",
      level: "intermediate",
      format: "casual",
      environment: "outdoor",
      equipmentNeeded: true,
      equipment: "Своя ракетка",
      bring: "Ракетка, кроссовки, вода",
      requirements: "Уметь держать розыгрыш",
      organizerTips: "Корт оплачен на 90 минут",
      durationMinutes: 90,
    },
  ),
  sportSeed(
    "demo-sport-running",
    "🏃",
    { ru: "Бег", uk: "Біг", cs: "Běh", en: "Running" },
    { ru: "Утренний лёгкий бег", uk: "Ранковий легкий біг", cs: "Ranní lehký běh", en: "Easy morning run" },
    {
      ru: "5 км в разговорном темпе, без гонки.",
      uk: "5 км у розмовному темпі, без перегонів.",
      cs: "5 km konverzačním tempem, bez závodu.",
      en: "5 km conversational pace, no racing.",
    },
    "2026-07-11",
    "08:30",
    "Korunní pevnůstka, Olomouc",
    0,
    12,
    4,
    {
      sportType: "Running",
      level: "beginner",
      format: "training",
      environment: "outdoor",
      equipmentNeeded: false,
      bring: "Кроссовки, вода",
      requirements: "Темп около 6:30-7:00 мин/км",
      organizerTips: "После бега кофе рядом",
      durationMinutes: 45,
    },
  ),
  sportSeed(
    "demo-sport-cycling",
    "🚴",
    { ru: "Велосипед", uk: "Велосипед", cs: "Kolo", en: "Cycling" },
    { ru: "Велозаезд вокруг города", uk: "Велозаїзд навколо міста", cs: "Vyjížďka kolem města", en: "City cycling loop" },
    {
      ru: "Неспешный маршрут 18 км с остановками.",
      uk: "Неквапливий маршрут 18 км із зупинками.",
      cs: "Pohodová trasa 18 km se zastávkami.",
      en: "Easy 18 km route with stops.",
    },
    "2026-07-12",
    "10:00",
    "Horní náměstí, Olomouc",
    0,
    14,
    7,
    {
      sportType: "Cycling",
      level: "intermediate",
      format: "casual",
      environment: "outdoor",
      equipmentNeeded: true,
      equipment: "Свой велосипед",
      bring: "Шлем, вода, замок",
      requirements: "Уверенно ехать по городу",
      organizerTips: "Едем группой, никого не бросаем",
      durationMinutes: 120,
    },
  ),
  sportSeed(
    "demo-sport-inline",
    "🛼",
    { ru: "Ролики", uk: "Ролики", cs: "Inline bruslení", en: "Inline skating" },
    { ru: "Ролики в парке", uk: "Ролики в парку", cs: "Inline v parku", en: "Inline skating in the park" },
    {
      ru: "Круги по ровной дорожке, подойдёт для спокойного катания.",
      uk: "Кола рівною доріжкою, підходить для спокійного катання.",
      cs: "Okruhy po rovné cestě, vhodné pro pohodovou jízdu.",
      en: "Loops on a flat path, good for relaxed skating.",
    },
    "2026-07-12",
    "18:00",
    "Smetanovy sady, Olomouc",
    0,
    10,
    3,
    {
      sportType: "Inline skating",
      level: "beginner",
      format: "casual",
      environment: "outdoor",
      equipmentNeeded: true,
      equipment: "Свои ролики",
      bring: "Защита, вода",
      requirements: "Уметь тормозить",
      organizerTips: "Если дорожка мокрая, перенесём",
      durationMinutes: 60,
    },
  ),
  sportSeed(
    "demo-sport-hiking",
    "🥾",
    { ru: "Поход", uk: "Похід", cs: "Výlet", en: "Hiking" },
    { ru: "Мини-поход на Святой Копечек", uk: "Міні-похід на Святий Копечек", cs: "Krátký výlet na Svatý Kopeček", en: "Short hike to Svatý Kopeček" },
    {
      ru: "Маршрут без спешки, по пути сделаем остановку на чай.",
      uk: "Маршрут без поспіху, дорогою зробимо зупинку на чай.",
      cs: "Trasa bez spěchu, cestou zastávka na čaj.",
      en: "No-rush route with a tea stop on the way.",
    },
    "2026-07-13",
    "09:30",
    "Olomouc hlavní nádraží",
    40,
    16,
    8,
    {
      sportType: "Hiking",
      level: "beginner",
      format: "casual",
      environment: "outdoor",
      equipmentNeeded: false,
      bring: "Удобная обувь, вода, перекус",
      requirements: "Около 9 км пешком",
      organizerTips: "Проверим погоду утром",
      durationMinutes: 180,
    },
  ),
  sportSeed(
    "demo-sport-swimming",
    "🏊",
    { ru: "Плавание", uk: "Плавання", cs: "Plavání", en: "Swimming" },
    { ru: "Бассейн без соревнований", uk: "Басейн без змагань", cs: "Bazén bez závodění", en: "Pool session without racing" },
    {
      ru: "Плаваем в своём темпе, потом короткая сауна.",
      uk: "Плаваємо у своєму темпі, потім коротка сауна.",
      cs: "Plaveme vlastním tempem, potom krátká sauna.",
      en: "Swim at your own pace, short sauna after.",
    },
    "2026-07-14",
    "20:00",
    "Plavecký stadion Olomouc",
    150,
    8,
    4,
    {
      sportType: "Swimming",
      level: "intermediate",
      format: "training",
      environment: "indoor",
      equipmentNeeded: false,
      bring: "Купальник, шапочка, полотенце",
      requirements: "Уметь проплыть 200 м",
      organizerTips: "Билеты покупаем на месте",
      durationMinutes: 75,
    },
  ),
  sportSeed(
    "demo-sport-badminton",
    "🏸",
    { ru: "Бадминтон", uk: "Бадмінтон", cs: "Badminton", en: "Badminton" },
    { ru: "Бадминтон в зале", uk: "Бадмінтон у залі", cs: "Badminton v hale", en: "Indoor badminton" },
    {
      ru: "Две площадки, меняемся парами каждые 15 минут.",
      uk: "Два корти, міняємося парами кожні 15 хвилин.",
      cs: "Dva kurty, páry střídáme každých 15 minut.",
      en: "Two courts, rotating pairs every 15 minutes.",
    },
    "2026-07-15",
    "18:00",
    "Omega centrum sportu, Olomouc",
    160,
    8,
    5,
    {
      sportType: "Badminton",
      level: "beginner",
      format: "training",
      environment: "indoor",
      equipmentNeeded: true,
      equipment: "Ракетки можно взять у организатора",
      bring: "Чистая обувь в зал",
      requirements: "Подходит для новичков",
      organizerTips: "Воланы уже куплены",
      durationMinutes: 90,
    },
  ),
  sportSeed(
    "demo-sport-fitness",
    "🏋️",
    { ru: "Фитнес", uk: "Фітнес", cs: "Fitness", en: "Fitness" },
    { ru: "Функциональная тренировка", uk: "Функціональне тренування", cs: "Funkční trénink", en: "Functional training" },
    {
      ru: "Круговая тренировка с адаптацией под уровень.",
      uk: "Колове тренування з адаптацією під рівень.",
      cs: "Kruhový trénink s úpravou podle úrovně.",
      en: "Circuit workout adapted to your level.",
    },
    "2026-07-16",
    "19:15",
    "Fitcentrum Best, Olomouc",
    220,
    6,
    3,
    {
      sportType: "Fitness",
      level: "advanced",
      format: "training",
      environment: "indoor",
      equipmentNeeded: false,
      bring: "Полотенце, вода",
      requirements: "Без острых травм",
      organizerTips: "Нагрузка регулируется",
      durationMinutes: 60,
    },
  ),
];
